### ISSUE TITLE
Module assumes that installed haproxy version is 1.5.x

### ISSUE THREAD

**Issue by altvnk** [arioch/puppet-haproxy#4]
But on Debian 7.x and 6.x it needs some additional steps outside the module to install haproxy 1.5.x.
Therefore haproxy 1.4.x does not start, because of SSL options in default config.
Maybe it can be useful to install 1.4.x without SSL in default config on Squeeze. And add back ports and repo http://haproxy.debian.net on Wheezy including SSL in default config.

Personally i added some puppet code to install those repos as dependency class in haproxy profile class.

Something like this:

``` puppet
  # Initialise wheezy back port repo
  class { 'apt::backports': }

  # Add repo key
  # deb http://haproxy.debian.net wheezy-backports main
  # Key: 46925553  Server: haproxy.debian.net

  # Add haproxy backports repo, and pin priority to ensure
  # that package from this repo will be installed
  apt::source { 'haproxy':
    location          => 'http://haproxy.debian.net',
    release           => 'wheezy-backports',
    repos             => 'main',
    include_src       => false,
    required_packages => 'debian-keyring debian-archive-keyring',
    key               => '353525F9',
    key_source        => 'http://haproxy.debian.net/bernat.debian.org.gpg',
    pin               => '200',
  }
```

**Comment by arioch** [comment]
This should be fixed in d7b5c4df847159fa283adae4610aaac4a3be47bd.
